name: flutter_ai_app
description: "Application de détection d'objets en temps réel"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  tflite: ^1.1.2
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/detect.tflite
    - assets/models/labelmap.txt 